---
title: "Initial"
author: "Sreeja Nair"
date: "October 17, 2018"
output:
  html_document: default
  word_document: default
fig_width: 14
fig_height: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
library(siverse)
library(tidyverse)
library(tidycensus)
library(scales)

theme_set(theme_minimal())
theme_update(text = element_text(family = "Roboto"), axis.text = element_text(family = "Roboto"), strip.text = element_text(family = "Roboto"), axis.text.x = element_text(angle = 45, hjust = 1))
options(scipen = 100)



```

```{r load data, include=FALSE}

datapath <- path_expand("G:/My Drive/SI/Current Projects/CRA Needs Assessment/WS 2_Analysis of Publicly Available Data/Data/")

wic <- read.csv("G:/My Drive/SI/Current Projects/CRA Needs Assessment/WS 2_Analysis of Publicly Available Data/Data/WIC_Clinics_in_Utah.csv") %>% clean_names()

poverty <- read.csv(path(datapath,"Poverty_data_by_Age__City_and_County_Utah_2013.csv")) %>% clean_names()

education <- read.csv(path(datapath, "Utah_Educational_Level_By_Census_Tract_2013.csv")) %>% clean_names()

hud <- read.csv(path(datapath, "County_HUD_Data_Utah_2011.csv")) %>% clean_names()

homelessness <- read.csv(path(datapath, "ut_homelessness.csv")) 

var <- load_variables(2017, "acs1", cache = TRUE) #List variables for ACS 1 year

var5 <- load_variables(2016,"acs5", cache =TRUE)




```



```{r wic, echo=FALSE, message=FALSE, warning=FALSE}

# separate address to its components

wic1 <- wic %>% separate(location_1, c("address","city1","geo"), sep = "\\n", remove = FALSE) %>% 
  separate(city1, c("city","state"), sep="\\,", remove = FALSE )

wic1 %>% 
  group_by(health_department) %>% 
  count() %>% 
  ggplot(aes(x = reorder(health_department,-n), y= n , fill = n)) +
  geom_bar(stat = "identity")+
  labs(title = " Distribution of WIC Clinics in Utah",
       x = "WIC Clinic Locations", y = "Count")+
  scale_fill_gradient(low = "red", high = "darkred")
  
#Maps?
```



```{r poverty, echo=FALSE}

#Create County dataset

pov_county <- poverty %>% 
  mutate(county1 = str_replace_all(county, '[ \t]+$', "")) %>% 
  mutate(county1 = case_when(county1 == "San Juabn"~"San Juan",
                             TRUE~county1))

pov_county %>% 
  group_by(county1) %>% 
  summarize(avg_median_income = mean(median_household_income, na.rm = TRUE)) %>% 
  ggplot(aes(x = reorder(county1, -avg_median_income), y = avg_median_income, fill = avg_median_income))+
  geom_bar(stat = "identity")+
  labs(title = "Average Median Income by County", x = "County", y = "Average Median Income")+
  scale_fill_gradient(low = "red", high = "darkred")

pov_county %>%  
  group_by(county1) %>% 
  summarize(avg_gini_index = mean(gini_index, na.rm = TRUE)) %>% 
  ggplot(aes(x = reorder(county1, -avg_gini_index), y = avg_gini_index, fill = avg_gini_index))+
  geom_bar(stat = "identity")+
  labs(title = "Average Gini Index by County", x = "County", y = "Average Gini Index")+
  scale_fill_gradient(low = "red", high = "darkred")
  
pov_county %>%  
  group_by(county1) %>% 
  summarize(avg_below_poverty_level = mean(below_poverty_level, na.rm = TRUE)) %>% 
  ggplot(aes(x = reorder(county1, -avg_below_poverty_level), y = avg_below_poverty_level, fill = avg_below_poverty_level))+
  geom_bar(stat = "identity")+
  labs(title = "Average Population Below Poverty Level by County", x = "County", y = "Average Population Below Poverty Level")+
  scale_fill_gradient(low = "red", high = "darkred")

pov_county %>% 
  mutate(total_pop = below_poverty_level+ at_or_above_poverty_level) %>% 
  group_by(county1) %>% 
  summarise(tot_below_poverty = sum(below_poverty_level),
            tot_above_poverty = sum(at_or_above_poverty_level),
            agg_total_pop = sum(total_pop),
            poverty_rate = tot_below_poverty/agg_total_pop) %>% 
  ggplot(aes(x = reorder(county1, -poverty_rate), y = poverty_rate, fill = poverty_rate))+
  geom_bar(stat = "identity")+
  labs(title = "Average Poverty Rate by County", x = "County", y = "Average Poverty Rate")+
  scale_fill_gradient(low = "red", high = "darkred")
  

#Create City dataset

pov_city <- poverty %>% 
 separate(location_1, c("city1","geo"), sep = "\\(", remove = FALSE) %>% 
  separate(city1, c("city","state"), sep="\\,", remove = FALSE ) %>% 
  select(-city1)


pov_city %>% 
  arrange(desc(below_poverty_level)) %>% 
  slice(1:10) %>% 
  ggplot(aes(x = reorder(city, -below_poverty_level), y = below_poverty_level, fill = below_poverty_level))+
  geom_bar(stat = "identity")+
  labs(title = "Top 10 Cities with highest populations below poverty level",
       x = "City", y = "Population below poverty level")+
  scale_fill_gradient(low = "red", high = "darkred")

pov_city %>% 
  mutate(total_pop = below_poverty_level+ at_or_above_poverty_level,
         poverty_rate = below_poverty_level/total_pop) %>% 
  arrange(desc(poverty_rate)) %>% 
  slice(1:10) %>% 
  ggplot(aes(x = reorder(city, -poverty_rate), y = poverty_rate, fill = poverty_rate))+
  geom_bar(stat = "identity")+
  labs(title = "Top 10 Cities with highest poverty rates",
       x = "City", y = "Poverty rates")+
  scale_fill_gradient(low = "red", high = "darkred")

pov_city %>% 
  arrange(desc(gini_index)) %>% 
  slice(1:10) %>% 
  ggplot(aes(x = reorder(city, -gini_index), y = gini_index, fill = gini_index))+
  geom_bar(stat = "identity")+
  labs(title = "Top 10 Cities with highest Gini index",
       x = "City", y = "Gini Index")+
  scale_fill_gradient(low = "red", high = "darkred")

pov_city %>% 
  arrange((gini_index)) %>% 
  slice(1:10) %>% 
  ggplot(aes(x = reorder(city, gini_index), y = gini_index, fill = gini_index))+
  geom_bar(stat = "identity")+
  labs(title = "Top 10 Cities with lowest Gini index",
       x = "City", y = "Gini Index")+
  scale_fill_gradient(low = "red", high = "darkred")

pov_city %>% 
  mutate(total_pop = below_poverty_level+ at_or_above_poverty_level,
         poverty_rate = below_poverty_level/total_pop,
         total_below_poverty_males = below_poverty_level_male+at_or_above_poverty_level_male,
         total_below_poverty_females = below_poverty_level_female+at_or_above_poverty_level_female) %>%  
  arrange(desc(poverty_rate)) %>% 
  slice(1:10) %>% 
  select(city, total_below_poverty_males,total_below_poverty_females) %>% 
  rename(male = total_below_poverty_males,
         female = total_below_poverty_females) %>% 
  gather("sex","poverty_rates",2:3) %>% 
  ggplot(aes(x = city, y = poverty_rates, fill = sex))+
  geom_bar(stat = "identity", position = "dodge")+
  labs(title = "Distribution of poverty rates of males and females amongst the top 10 cities with highest poverty levels",
       x = "City", y = "Poverty rates")+
  scale_fill_manual(values = c("#CF3721","#31a9b8")) #(27.cheerfulbrights-color ref)
  

```





```{r HUD, echo=FALSE}

hud %>% 
  filter(program_label == "Summary of All HUD Programs") %>% 
  filter(name!="No county code", 
         total_units > quantile(total_units, 0.25, na.rm = T)) %>% 
  ggplot(aes(x = reorder(name, -total_units), y = total_units, fill = total_units))+
  geom_bar(stat = "identity")+
  labs(title = "Total number of units(all HUD) by County",  
       x = "County", y = "Total Units")+
  scale_fill_gradient(low = "red", high = "darkred")

hud %>% 
  filter(program_label == "LIHTC") %>% 
  filter(name!="No county code", 
         total_units > quantile(total_units, 0.25, na.rm = T)) %>% 
  ggplot(aes(x = reorder(name, -total_units), y = total_units, fill = total_units))+
  geom_bar(stat = "identity")+
  labs(title = "Total number of units(LIHTC) by County",  
       x = "County", y = "Total Units")+
  scale_fill_gradient(low = "red", high = "darkred")

hud %>% 
  filter(program_label == "Housing Choice Vouchers") %>% 
  filter(name!="No county code", 
         total_units > quantile(total_units, 0.25, na.rm = T)) %>% 
  ggplot(aes(x = reorder(name, -total_units), y = total_units, fill = total_units))+
  geom_bar(stat = "identity")+
  labs(title = "Total number of units(Housing Choice Vouchers) by County",  
       x = "County", y = "Total Units")+
  scale_fill_gradient(low = "red", high = "darkred")


hud %>% 
  filter(program_label == "Summary of All HUD Programs") %>% 
  filter(name!="No county code", 
         pct_occupied > 0) %>% 
  ggplot(aes(x = reorder(name, -pct_occupied), y = pct_occupied, fill = pct_occupied))+
  geom_bar(stat = "identity")+
  labs(title = "Percent Occupied (all HUD) by County",  
       x = "County", y = "Percent Occupied")+
  scale_fill_gradient(low = "red", high = "darkred")

hud %>% 
  filter(program_label == "Housing Choice Vouchers") %>% 
  filter(name!="No county code", 
         pct_occupied > 0) %>% 
  ggplot(aes(x = reorder(name, -pct_occupied), y = pct_occupied, fill = pct_occupied))+
  geom_bar(stat = "identity")+
  labs(title = "Percent Occupied(Housing Choice Vouchers) by County",  
       x = "County", y = "Percent Occupied")+
  scale_fill_gradient(low = "red", high = "darkred")
  

hud %>% 
  filter(program_label == "Summary of All HUD Programs",
         rent_per_month>0,
         hh_income>0) %>%
  mutate(rent_as_pct_income = rent_per_month/hh_income) %>% 
  ggplot(aes(x=reorder(name,-rent_as_pct_income), y = rent_as_pct_income, fill =rent_as_pct_income))+
  geom_bar(stat = "identity")+
  labs(title = "Rent as percent of income", x = "County", y="Percentage")+
  scale_fill_gradient(low = "red", high = "darkred")


hud %>% 
  filter(program_label == "Summary of All HUD Programs",
         name!="No county code",
         months_waiting>0) %>%
  ggplot(aes(x=reorder(name,-months_waiting), y = months_waiting, fill =months_waiting))+
  geom_bar(stat = "identity")+
  labs(title = "Months waiting (all HUD)", x = "County", y="Months")+
  scale_fill_gradient(low = "red", high = "darkred")  

hud %>% 
  filter(program_label == "Summary of All HUD Programs",
         name!="No county code",
         months_from_movein>0) %>%
  ggplot(aes(x=reorder(name,-months_from_movein), y = months_from_movein, fill =months_from_movein))+
  geom_bar(stat = "identity")+
  labs(title = "Months from move in (all HUD)", x = "County", y="Months")+
  scale_fill_gradient(low = "red", high = "darkred")

hud %>% 
  filter(program_label == "Summary of All HUD Programs",
         name!="No county code",
         pct_minority>0) %>%
  ggplot(aes(x=reorder(name,-pct_minority), y = pct_minority, fill =pct_minority))+
  geom_bar(stat = "identity")+
  labs(title = "Percent minority (all HUD)", x = "County", y="percentage")+
  scale_fill_gradient(low = "red", high = "darkred")


  

```


```{r homelessness, echo=FALSE}

homelessness %>% 
  filter(category == "Sheltered Headcount", type == "Total") %>% 
  select(county, x2011, x2012, x2013, x2014) %>% 
  gather("years", "count", 2:5) %>% 
  mutate(years = case_when(years == "x2011"~"2011",
                           years == "x2012"~"2012",
                           years == "x2013"~"2013",
                           years == "x2014"~"2014"),
         years = as.numeric(years)) %>%
  ggplot(aes(x = years, y = count, color = county))+
  geom_line(size =1) +
  labs(title = "Sheltered homeless headcounts over time", 
       x = "Years", y = "Sheltered Homeless Headcount")

homelessness %>% 
  filter(category == "Sheltered Household", type == "Total") %>% 
  select(county, x2011, x2012, x2013, x2014) %>% 
  gather("years", "count", 2:5) %>% 
  mutate(years = case_when(years == "x2011"~"2011",
                           years == "x2012"~"2012",
                           years == "x2013"~"2013",
                           years == "x2014"~"2014"),
         years = as.numeric(years)) %>%
  ggplot(aes(x = years, y = count, color = county))+
  geom_line(size =1) +
  labs(title = "Sheltered homeless households over time", 
       x = "Years", y = "Sheltered Homeless Households")


homelessness %>% 
  filter(category == "Unsheltered Headcount", type == "Total") %>% 
  select(county, x2011, x2012, x2013, x2014) %>% 
  gather("years", "count", 2:5) %>% 
  mutate(years = case_when(years == "x2011"~"2011",
                           years == "x2012"~"2012",
                           years == "x2013"~"2013",
                           years == "x2014"~"2014"),
         years = as.numeric(years)) %>%
  ggplot(aes(x = years, y = count, color = county))+
  geom_line(size =1) +
  labs(title = "Unsheltered homeless headcount over time", 
       x = "Years", y = "Unsheltered Homeless Headcount")
 
homelessness %>% 
  filter(category == "Unsheltered Household", type == "Total") %>% 
  select(county, x2011, x2012, x2013, x2014) %>% 
  gather("years", "count", 2:5) %>% 
  mutate(years = case_when(years == "x2011"~"2011",
                           years == "x2012"~"2012",
                           years == "x2013"~"2013",
                           years == "x2014"~"2014"),
         years = as.numeric(years)) %>%
  ggplot(aes(x = years, y = count, color = county))+
  geom_line(size =1) +
  labs(title = "Unsheltered homeless households over time", 
       x = "Years", y = "Unsheltered Homeless Households")
  
homelessness %>% 
  filter(county=="Salt Lake",
         type=="Total",
         !str_detect(category,"Total")) %>% 
  select(category,x2011, x2012, x2013, x2014) %>% 
  gather("years", "count", 2:5) %>% 
  mutate(years = case_when(years == "x2011"~"2011",
                           years == "x2012"~"2012",
                           years == "x2013"~"2013",
                           years == "x2014"~"2014"),
         years = as.numeric(years)) %>% 
  ggplot(aes(x = years, y = count, color = category))+
  geom_line(size =1)+
  labs(title = "Salt Lake County over time", x = "Years", y = "Counts")


```



```{r education, eval=FALSE, include=FALSE}


  

```



```{r ACS poverty, eval=FALSE, include=FALSE}

pverty2 <- get_acs(geography = "county"
                   variables = "S2201_C01_001E",
                   survey = "acs5",
                   state = "UT")

pverty2.2 <- get_acs(geography = "county",
                   variables = "S2201_C02_001E",
                   survey = "acs5",
                   state = "UT")


```


```{r ACS unemployment, echo=FALSE, message=FALSE, warning=FALSE}

emp_tot <- map_df(2012:2017, function(x){
  get_acs(geography = "county",
          variables = c(tot = "B23025_001"),
          state = "UT",
          survey = "acs1",
          year = x) %>% 
    mutate(year = x) %>% 
    rename(tot_estimate = estimate,
           tot_moe = moe) %>% 
    select(-variable)
})

unemp<- map_df(2012:2017, function(x){
  get_acs(geography = "county",
          variables = c(unemp = "B23025_007"),
          state = "UT",
          survey = "acs1",
          year = x) %>% 
    mutate(year = x) %>% 
    rename(unemp_estimate = estimate,
           unemp_moe = moe) %>% 
    select(-variable)
})

emp <- left_join(emp_tot,unemp)

emp %>% 
  mutate(NAME = str_replace(NAME, ", Utah", ""),
         pct_unemp = unemp_estimate/tot_estimate) %>% 
  ggplot(aes(x = year, y = pct_unemp, color = NAME))+
  geom_line(size= 1)+
  labs(title = "Unemployment Percentage by County per Year", x = "Year", y = "Percentage")+
  scale_y_continuous(labels = percent)
                        
```



```{r SNAP}

snap_usage <- map_df(2012:2017, function(x){
  get_acs(geography = "county",
          variables = c(tot_SNAP = "C22001_001",
                        SNAP_recd = "C22001_002",
                        SNAP_not_recd = "C22001_003",
                        SNAP_by_pov = "B22003_001",
                        SNAP_by_pov_BPL = "B22003_003",
                        SNAP_by_pov_APL = "B22003_004",
                        noSNAP_by_pov_BPL = "B22003_006",
                        noSNAP_by_pov_APL = "B22003_007"),
          state = "UT",
          survey = "acs1",
          year = x) %>% 
    mutate(year = x) #do we need to use race variables here? 
})


snap_usage %>% 
  mutate(NAME = str_replace(NAME, ", Utah", "")) %>% 
  filter(variable == "tot_SNAP") %>% 
  ggplot(aes(x = year, y = estimate, color = NAME))+
  geom_line(size = 1)+
  labs(title = "SNAP usage (past 12 months) for households", x ="Year", y = "SNAP Usage") #What is this?

snap_usage %>% 
  mutate(NAME = str_replace(NAME, ", Utah", "")) %>% 
  filter(variable == "SNAP_recd") %>% 
  ggplot(aes(x = year, y = estimate, color = NAME))+
  geom_line(size = 1)+
  labs(title = "SNAP received (past 12 months) for households", x ="Year", y = "SNAP Usage")

snap_usage %>% 
  mutate(NAME = str_replace(NAME, ", Utah", "")) %>% 
  filter(variable == "SNAP_not_recd") %>% 
  ggplot(aes(x = year, y = estimate, color = NAME))+
  geom_line(size = 1)+
  labs(title = "SNAP not received (past 12 months) for households", x ="Year", y = "SNAP Usage")

snap_usage %>% 
  mutate(NAME = str_replace(NAME, ", Utah", "")) %>% 
  filter(variable == "SNAP_by_pov_BPL") %>% 
  ggplot(aes(x = year, y = estimate, color = NAME))+
  geom_line(size = 1)+
  labs(title = "SNAP received (past 12 months) for households below poverty line", x ="Year", y = "SNAP Usage")

snap_usage %>% 
  mutate(NAME = str_replace(NAME, ", Utah", "")) %>% 
  filter(variable == "noSNAP_by_pov_BPL") %>% 
  ggplot(aes(x = year, y = estimate, color = NAME))+
  geom_line(size = 1)+
  labs(title = "SNAP not received (past 12 months) for households below poverty line", x ="Year", y = "SNAP Usage")  
  
```


```{r Median Income}

median_income <- map_df(2012:2017, function(x){
  get_acs(geography = "county",
          variables = c(hhincome = "B19013_001"),
          state = "UT",
          survey = "acs1",
          year = x) %>% 
    mutate(year = x) 
})

median_income %>% 
  mutate(NAME = str_replace(NAME, ", Utah", "")) %>% 
  ggplot(aes(x = year, y= estimate, color = NAME))+
  geom_line(size =1)+
  labs(title = "Median Household income", x = "Year", y = "Income")+
  scale_y_continuous(labels = dollar)


family_income <- map_df(2012:2017, function(x){
  get_acs(geography = "county",
          variables = c(famincome = "B19101_001"),
          state = "UT",
          survey = "acs1",
          year = x) %>% 
    mutate(year = x) 
})

family_income %>% 
  mutate(NAME = str_replace(NAME, ", Utah", "")) %>% 
  ggplot(aes(x = year, y= estimate, color = NAME))+
  geom_line(size =1)+
  labs(title = "Family income", x = "Year", y = "Income")+
  scale_y_continuous(labels = dollar)

family_income_5 <- get_acs(geography = "county",
          variables = c(famincome = "B19101_001"),
          state = "UT",
          survey = "acs5")


family_income_5 %>% 
  mutate(NAME = str_replace(NAME, ", Utah", "")) %>% 
  ggplot(aes(x = reorder(NAME, -estimate),y = estimate)) + 
  geom_errorbar(aes(ymin = estimate - moe, ymax = estimate + moe)) + 
  geom_point(size = 3, color = "red")+
  labs(title = "Family Income per County", x = "County",  y ="Family Income")+
  scale_y_continuous(labels = dollar)

```


```{r}

```

